name: dry
description: web components
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  global_configuration: ^2.0.0-nullsafety.0
  json_annotation: ^4.0.1
  intl: ^0.17.0
  fluttertoast: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.12 # flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^4.1.3

flutter_intl:
  enabled: true
